export const VIGNETTE_SNAPSHOT_ROWS: Array<Record<string, string>> = [
  {
    'Timestamp': '10/12/2025 14:22:10',
    'Email address': 'director.cinemaparadiso@gmail.com',
    'Team Name': 'CINEMA PARADISO',
    "Team Leader's mail ID": 'lead.paradiso@nid.ac.in',
    'College Name': 'National Institute of Design, Ahmedabad',
    'Final Submission': 'https://drive.google.com/file/d/1vignette_cinema_paradiso/view?usp=sharing',
  },
  {
    'Timestamp': '10/12/2025 16:45:33',
    'Email address': 'framebyframe.films@spa.ac.in',
    'Team Name': 'FRAME BY FRAME',
    "Team Leader's mail ID": 'kavya.verma@spa.ac.in',
    'College Name': 'School of Planning and Architecture, Delhi',
    'Final Submission': 'https://drive.google.com/file/d/1frame_by_frame_vignette/view?usp=sharing',
  },
  {
    'Timestamp': '10/13/2025 09:12:05',
    'Email address': 'aurora.creatives@iitb.ac.in',
    'Team Name': 'THE AURORA',
    "Team Leader's mail ID": 'samir.aurora@iitb.ac.in',
    'College Name': 'IIT Bombay',
    'Final Submission': 'https://youtu.be/aurora_film_entry_2026',
  },
  {
    'Timestamp': '10/13/2025 11:30:20',
    'Email address': 'obscura.celluloid@nift.ac.in',
    'Team Name': 'OBSCURA',
    "Team Leader's mail ID": 'tanya.obscura@nift.ac.in',
    'College Name': 'NIFT Delhi',
    'Final Submission': 'https://drive.google.com/file/d/1obscura_film_nift/view?usp=sharing',
  },
  {
    'Timestamp': '10/13/2025 15:10:44',
    'Email address': 'montage.studios@srfti.ac.in',
    'Team Name': 'MONTAGE STUDIOS',
    "Team Leader's mail ID": 'arjun.sen@srfti.ac.in',
    'College Name': 'Satyajit Ray Film and Television Institute, Kolkata',
    'Final Submission': 'https://vimeo.com/montage_studios_vignette',
  },
  {
    'Timestamp': '10/14/2025 10:05:12',
    'Email address': 'lenscraft.iimi@iimidr.ac.in',
    'Team Name': 'LENSCRAFT PRODUCTIONS',
    "Team Leader's mail ID": 'ananya.p@iimidr.ac.in',
    'College Name': 'IIM Indore',
    'Final Submission': 'https://drive.google.com/file/d/1lenscraft_arb26/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 13:40:55',
    'Email address': 'parallax.cinema@bits-pilani.ac.in',
    'Team Name': 'PARALLAX FILMS',
    "Team Leader's mail ID": 'dev.parallax@bits-pilani.ac.in',
    'College Name': 'BITS Pilani',
    'Final Submission': 'https://youtu.be/parallax_arb26_vignette',
  },
  {
    'Timestamp': '10/14/2025 18:22:01',
    'Email address': 'anamorphic.media@srishti.ac.in',
    'Team Name': 'ANAMORPHIC DREAMS',
    "Team Leader's mail ID": 'riya.k@srishti.ac.in',
    'College Name': 'Srishti Institute of Art, Design and Technology, Bengaluru',
    'Final Submission': 'https://drive.google.com/file/d/1anamorphic_dreams_film/view?usp=sharing',
  },
];

export const PICASSOS_PIXELS_SNAPSHOT_ROWS: Array<Record<string, string>> = [
  {
    'Timestamp': '10/12/2025 11:04:12',
    'Email Address': 'rishabh.jain@nid.ac.in',
    'Participant Name': 'RISHABH JAIN',
    'Participant Contact Number': '9876543210',
    'Participant E-mail ID': 'rishabh.jain@nid.ac.in',
    'Participant College Name': 'National Institute of Design, Ahmedabad',
    'Participant College ID': 'NID-DES-2026-0492',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1rishabh_timelapse_art/view?usp=sharing',
  },
  {
    'Timestamp': '10/12/2025 13:20:45',
    'Email Address': 'aisha.patel@srishti.ac.in',
    'Participant Name': 'AISHA PATEL',
    'Participant Contact Number': '9812345678',
    'Participant E-mail ID': 'aisha.patel@srishti.ac.in',
    'Participant College Name': 'Srishti Institute of Art, Design and Technology, Bengaluru',
    'Participant College ID': 'SRI-ART-1104',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1aisha_digitalart_timelapse/view?usp=sharing',
  },
  {
    'Timestamp': '10/12/2025 15:40:19',
    'Email Address': 'vikram.chouhan@jjiaa.edu.in',
    'Participant Name': 'VIKRAM CHOUHAN',
    'Participant Contact Number': '9723456789',
    'Participant E-mail ID': 'vikram.chouhan@jjiaa.edu.in',
    'Participant College Name': 'Sir J. J. Institute of Applied Art, Mumbai',
    'Participant College ID': 'JJ-IAA-0881',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://youtu.be/vikram_timelapse_art',
  },
  {
    'Timestamp': '10/12/2025 17:15:30',
    'Email Address': 'meera.nair@nift.ac.in',
    'Participant Name': 'MEERA NAIR',
    'Participant Contact Number': '9634567890',
    'Participant E-mail ID': 'meera.nair@nift.ac.in',
    'Participant College Name': 'NIFT Mumbai',
    'Participant College ID': 'NFT-MUM-2341',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1meera_nift_art_timelapse/view?usp=sharing',
  },
  {
    'Timestamp': '10/13/2025 09:30:11',
    'Email Address': 'aditya.sharma@iitd.ac.in',
    'Participant Name': 'ADITYA SHARMA',
    'Participant Contact Number': '9545678901',
    'Participant E-mail ID': 'aditya.sharma@iitd.ac.in',
    'Participant College Name': 'IIT Delhi',
    'Participant College ID': '2023CS10842',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1aditya_pixels_timelapse/view?usp=sharing',
  },
  {
    'Timestamp': '10/13/2025 10:45:50',
    'Email Address': 'kavita.deshmukh@mitid.edu.in',
    'Participant Name': 'KAVITA DESHMUKH',
    'Participant Contact Number': '9456789012',
    'Participant E-mail ID': 'kavita.deshmukh@mitid.edu.in',
    'Participant College Name': 'MIT Institute of Design, Pune',
    'Participant College ID': 'MITID-22-901',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1kavita_digital_illustration/view?usp=sharing',
  },
  {
    'Timestamp': '10/13/2025 12:18:22',
    'Email Address': 'tanmay.bose@iitkgp.ac.in',
    'Participant Name': 'TANMAY BOSE',
    'Participant Contact Number': '9367890123',
    'Participant E-mail ID': 'tanmay.bose@iitkgp.ac.in',
    'Participant College Name': 'IIT Kharagpur',
    'Participant College ID': 'KGP-DES-4412',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://youtu.be/tanmay_kgp_digitalart',
  },
  {
    'Timestamp': '10/13/2025 14:02:15',
    'Email Address': 'diya.sen@bhu.ac.in',
    'Participant Name': 'DIYA SEN',
    'Participant Contact Number': '9278901234',
    'Participant E-mail ID': 'diya.sen@bhu.ac.in',
    'Participant College Name': 'Faculty of Visual Arts, BHU Varanasi',
    'Participant College ID': 'BHU-FVA-782',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1diya_sen_timelapse/view?usp=sharing',
  },
  {
    'Timestamp': '10/13/2025 16:25:40',
    'Email Address': 'rohan.verma@dtu.ac.in',
    'Participant Name': 'ROHAN VERMA',
    'Participant Contact Number': '9189012345',
    'Participant E-mail ID': 'rohan.verma@dtu.ac.in',
    'Participant College Name': 'Delhi Technological University',
    'Participant College ID': '2K22/SE/112',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1rohan_dtu_art/view?usp=sharing',
  },
  {
    'Timestamp': '10/13/2025 18:50:00',
    'Email Address': 'ananya.kulkarni@symbiosis.ac.in',
    'Participant Name': 'ANANYA KULKARNI',
    'Participant Contact Number': '9090123456',
    'Participant E-mail ID': 'ananya.kulkarni@symbiosis.ac.in',
    'Participant College Name': 'Symbiosis Institute of Design, Pune',
    'Participant College ID': 'SID-2024-039',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1ananya_sid_pixels/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 09:15:30',
    'Email Address': 'harsh.vardhan@iitb.ac.in',
    'Participant Name': 'HARSH VARDHAN',
    'Participant Contact Number': '9988776655',
    'Participant E-mail ID': 'harsh.vardhan@iitb.ac.in',
    'Participant College Name': 'IDC School of Design, IIT Bombay',
    'Participant College ID': 'IDC-24-102',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1harsh_idc_timelapse/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 10:30:15',
    'Email Address': 'sneha.reddy@jntu.ac.in',
    'Participant Name': 'SNEHA REDDY',
    'Participant Contact Number': '9877665544',
    'Participant E-mail ID': 'sneha.reddy@jntu.ac.in',
    'Participant College Name': 'JNAFAU Hyderabad',
    'Participant College ID': 'JNAFAU-BFA-19',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1sneha_digital_art/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 11:45:00',
    'Email Address': 'karan.mehta@du.ac.in',
    'Participant Name': 'KARAN MEHTA',
    'Participant Contact Number': '9766554433',
    'Participant E-mail ID': 'karan.mehta@du.ac.in',
    'Participant College Name': 'College of Art, Delhi University',
    'Participant College ID': 'COA-DU-2025',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1karan_coa_timelapse/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 13:10:20',
    'Email Address': 'pooja.hegde@manipal.edu',
    'Participant Name': 'POOJA HEGDE',
    'Participant Contact Number': '9655443322',
    'Participant E-mail ID': 'pooja.hegde@manipal.edu',
    'Participant College Name': 'Manipal Academy of Higher Education',
    'Participant College ID': 'MAHE-DES-501',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1pooja_digital_submission/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 14:25:35',
    'Email Address': 'rahul.iyer@loyola.edu.in',
    'Participant Name': 'RAHUL IYER',
    'Participant Contact Number': '9544332211',
    'Participant E-mail ID': 'rahul.iyer@loyola.edu.in',
    'Participant College Name': 'Loyola College, Chennai',
    'Participant College ID': 'LOY-VISCOM-88',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1rahul_loyola_pixels/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 15:40:50',
    'Email Address': 'zoya.khan@jamia.ac.in',
    'Participant Name': 'ZOYA KHAN',
    'Participant Contact Number': '9433221100',
    'Participant E-mail ID': 'zoya.khan@jamia.ac.in',
    'Participant College Name': 'Faculty of Fine Arts, Jamia Millia Islamia',
    'Participant College ID': 'JMI-FFA-2023-4',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1zoya_jmi_timelapse/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 16:55:05',
    'Email Address': 'varun.gupta@iitk.ac.in',
    'Participant Name': 'VARUN GUPTA',
    'Participant Contact Number': '9322110099',
    'Participant E-mail ID': 'varun.gupta@iitk.ac.in',
    'Participant College Name': 'IIT Kanpur',
    'Participant College ID': '210984-DES',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1varun_iitk_art/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 17:30:40',
    'Email Address': 'kriti.saxena@christ.edu.in',
    'Participant Name': 'KRITI SAXENA',
    'Participant Contact Number': '9211009988',
    'Participant E-mail ID': 'kriti.saxena@christ.edu.in',
    'Participant College Name': 'Christ University, Bengaluru',
    'Participant College ID': 'CHR-MDA-992',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1kriti_christ_submission/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 18:15:10',
    'Email Address': 'abhishek.roy@ju.edu.in',
    'Participant Name': 'ABHISHEK ROY',
    'Participant Contact Number': '9100998877',
    'Participant E-mail ID': 'abhishek.roy@ju.edu.in',
    'Participant College Name': 'Jadavpur University, Kolkata',
    'Participant College ID': 'JU-ARTS-302',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1abhishek_ju_timelapse/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 19:00:25',
    'Email Address': 'tanya.sharma@nift.ac.in',
    'Participant Name': 'TANYA SHARMA',
    'Participant Contact Number': '9099887766',
    'Participant E-mail ID': 'tanya.sharma@nift.ac.in',
    'Participant College Name': 'NIFT Delhi',
    'Participant College ID': 'NFT-DEL-2024-81',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1tanya_nift_pixels/view?usp=sharing',
  },
  {
    'Timestamp': '10/14/2025 19:45:00',
    'Email Address': 'siddharth.m@iimidr.ac.in',
    'Participant Name': 'SIDDHARTH MENON',
    'Participant Contact Number': '9988998877',
    'Participant E-mail ID': 'siddharth.m@iimidr.ac.in',
    'Participant College Name': 'IIM Indore',
    'Participant College ID': 'IPM-2024-118',
    'Please upload your preliminary submission video below. Kindly ensure the timelapse video is no more than 5 minutes long.': 'https://drive.google.com/file/d/1siddharth_pixels_arb26/view?usp=sharing',
  },
];
